#!/usr/bin/env zsh

dependencies() {
    local filepath=$ZSH_DOTFILES/dependencies.ssv
    local result=()

    echo >$filepath
    brew leaves -r | while read -r p; do
        package_name=$(echo "$p" | awk -F '@' '{print $1}')
        package_version=$(brew info --json=v1 "$p" | jq -r '.[0].versions.stable')
        echo "${package_name}@${package_version}" >>$filepath
    done
    cat $filepath
}
