#!/usr/bin/env zsh

install() {
    local filepath=$ZSH_DOTFILES/dependencies.ssv
    if [[ ! -f $filepath ]]; then
        echo "Not found but required: $filepath"
        return 1
    fi

    while IFS= read -r package; do
        if [ -n "$package" ]; then
            local ok="Successfully installed"
            local err="Failed to install"

            if brew install "$package"; then
                echo "$ok $package"
            else
                echo "$err $package"
            fi
        fi
    done <"$filepath"
}
